# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa0d9784f10f541b84e7776b920aac34fbde2effea4b567f72aaab723d5a9a5a1b7cf1b9fecc060966d49bed5f35dba8fa67bfb8eab8f0e4370a157768e6e38

test:
  secret_key_base: d5ccdc34c4c6a25e0ba9eeef29502ff116ec02d3ed12ea936a8ecf37eeab37a715281fb6f606396f01fafded14a6e49cbf9d6877abe6155b4b65e2925f3cd236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
